services:
    
    smw-api:
        build: .
        container_name: smw-api
        ports:
            - "8000:8000"
        volumes:
            - ./app/:/src/project/app
            - ./logs/:/src/project/logs
        depends_on:
            - smw-db
        networks:
            - smw-net
        env_file:
            - .env
        environment:
            CONN_DB: "${CONN_DB}"
            JWT_SECRET_KEY: "${JWT_SECRET_KEY}"

    smw-db:
        image: postgres:16.3
        env_file:
            - .env
        environment:
            POSTGRES_DB: "save_my_wallet"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_USER: "${POSTGRES_USER}"
        ports:
            - "5433:5432"
        volumes:
            - "../smw-db:/var/lib/postgresql/data"
        networks:
            - smw-net

networks:
    smw-net: