services:
    smw-db:
        image: postgres:15.2
        environment:
            - POSTGRES_DB=save_my_wallet
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=root
        ports:
            - "5433:5432"
        volumes:
            - "../smw-db:/var/lib/postgresql/data"
