services:
    
    smw-api:
        build: .
        container_name: smw-api
        ports:
            - "8000:8000"
        volumes:
            - ./app:/srv/project/app
            - ./logs:/srv/project/logs
        depends_on:
            - smw-db
        networks:
            - smw-net
        env_file:
            - .env
        environment:
            CONN_DB: "${CONN_DB}"
            JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
            TZ: "America/Argentina/Mendoza"

    smw-db:
        image: postgres:16.3
        environment:
            POSTGRES_DB: "save_my_wallet"
        volumes:
            - "../smw-db:/var/lib/postgresql/data"
        networks:
            - smw-net

networks:
    smw-net: