"""Add payments table

Revision ID: 21e511cb461a
Revises: fe8c50fc25de
Create Date: 2023-08-14 21:00:52.641923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e511cb461a'
down_revision = 'fe8c50fc25de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('status', sa.Enum('UNCONFIRMED', 'CONFIRMED', 'PAID', 'CANCELED', name='statusenum'), nullable=False),
    sa.Column('amount', sa.Float(precision=2), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###
