"""Set main CC as nullable

Revision ID: 2a036fc4186f
Revises: 18d311806b6d
Create Date: 2023-07-12 00:25:15.995206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a036fc4186f'
down_revision = '18d311806b6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_cards', 'main_credit_card_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_cards', 'main_credit_card_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
