"""Add relation expense-category and spent_type field

Revision ID: 3f20c53cd027
Revises: 889335cb895f
Create Date: 2025-02-23 00:06:42.529098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f20c53cd027'
down_revision = '889335cb895f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('spent_type', sa.String(length=20), nullable=True))
    op.add_column('expenses', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'expense_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'category_id')
    op.drop_column('expenses', 'spent_type')
    # ### end Alembic commands ###
