"""Add installment_no col to statement_items table

Revision ID: 991c0f7911c0
Revises: f35a43e24a6e
Create Date: 2023-08-05 19:25:16.696474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991c0f7911c0'
down_revision = 'f35a43e24a6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statement_items', sa.Column('installment_no', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statement_items', 'installment_no')
    # ### end Alembic commands ###
