"""add colum paid to table credit_card_statements

Revision ID: a00744c1aab9
Revises: 991c0f7911c0
Create Date: 2023-08-05 23:54:54.953369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00744c1aab9'
down_revision = '991c0f7911c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_card_statements', sa.Column('paid', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_card_statements', 'paid')
    # ### end Alembic commands ###
