"""Add fields for alert amounts

Revision ID: adf58c15cfb5
Revises: e70e9438ef00
Create Date: 2024-06-04 15:50:37.305590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf58c15cfb5'
down_revision = 'e70e9438ef00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_cards', 'limit',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('expenses', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.add_column('profiles', sa.Column('spent_alert', sa.Float(precision=2), server_default='0.0', nullable=False))
    op.add_column('profiles', sa.Column('monthly_payment_alert', sa.Float(precision=2), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'monthly_payment_alert')
    op.drop_column('profiles', 'spent_alert')
    op.alter_column('payments', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('expenses', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('credit_cards', 'limit',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
