"""Init table schemas

Revision ID: b98a44c1c659
Revises: 
Create Date: 2024-05-18 23:22:04.575315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b98a44c1c659'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'COMMON', name='roleenum'), nullable=False),
    sa.Column('status', sa.Enum('UNCONFIRMED', 'CONFIRMED', 'BANNED', name='userstatusenum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('credit_cards',
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('limit', sa.Float(precision=2), nullable=False),
    sa.Column('main_credit_card_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('next_closing_date', sa.Date(), nullable=True),
    sa.Column('next_expiring_date', sa.Date(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['main_credit_card_id'], ['credit_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('cc_name', sa.String(length=100), nullable=False),
    sa.Column('acquired_at', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(precision=2), nullable=False),
    sa.Column('type', sa.Enum('PURCHASE', 'SUBSCRIPTION', name='expensetypeenum'), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=False),
    sa.Column('first_payment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FINISHED', name='expensestatusenum'), nullable=False),
    sa.Column('credit_card_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('status', sa.Enum('UNCONFIRMED', 'CONFIRMED', 'PAID', 'CANCELED', name='paymentstatusenum'), nullable=False),
    sa.Column('amount', sa.Float(precision=2), nullable=False),
    sa.Column('no_installment', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('expenses')
    op.drop_table('profiles')
    op.drop_table('credit_cards')
    op.drop_table('users')
    # ### end Alembic commands ###
