"""delete

Revision ID: d91970b2deef
Revises: 40eb168cdee6
Create Date: 2024-12-01 06:20:29.074933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91970b2deef'
down_revision = '40eb168cdee6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('credit_cards_account_id_fkey', 'credit_cards', type_='foreignkey')
    op.create_foreign_key('cc_ac_fk', 'credit_cards', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cc_ac_fk', 'credit_cards', type_='foreignkey')
    op.create_foreign_key('credit_cards_account_id_fkey', 'credit_cards', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###
