"""add columns for closing and expiring date for credit cards

Revision ID: df07dad2f6c9
Revises: dcc8ddd5dd8b
Create Date: 2023-10-14 16:57:13.890217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df07dad2f6c9'
down_revision = 'dcc8ddd5dd8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_cards', sa.Column('closing_date', sa.Date(), nullable=True))
    op.add_column('credit_cards', sa.Column('expiring_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_cards', 'expiring_date')
    op.drop_column('credit_cards', 'closing_date')
    # ### end Alembic commands ###
