"""Set cc_statement_id as nullable

Revision ID: ee1658a2b625
Revises: a00744c1aab9
Create Date: 2023-08-14 12:01:03.144564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1658a2b625'
down_revision = 'a00744c1aab9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statement_items', 'cc_statement_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statement_items', 'cc_statement_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
