"""Change cc limit from float to int

Revision ID: f35a43e24a6e
Revises: 2a036fc4186f
Create Date: 2023-07-12 19:29:59.242000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35a43e24a6e'
down_revision = '2a036fc4186f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
